K8SPS-53 document backups
percona/percona-server-mysql-operator pull request #100
Opened 2022-06-27 12:48 UTC by fiowro

2022-06-29 07:23 UTC, egegunes requested changes

2022-06-29 07:23 UTC, egegunes commented on source/backups.rst
> +backups are stored in the root directory.
it's not true in case of PS operator, it'll be implemented in the future

2022-06-29 07:23 UTC, egegunes commented on source/backups.rst
> +backups will be stored in the root directory of the container.
it's not true for this release

2022-06-29 08:03 UTC, tplavcic requested changes

2022-06-29 08:03 UTC, tplavcic commented on source/conf.py
>  ps80recommended = '8.0.25'
ps80recommended='8.0.28'
and for ps57 we don't support right now and I don't think we will.

2022-06-29 08:03 UTC, tplavcic commented on source/conf.py
>  pmm2recommended = '2.25.0'
pmm2recommended = '2.28.0'

2022-06-29 08:03 UTC, tplavcic commented on source/operator.rst
> +| **Example**     | ``percona/percona-xtrabackup:{{{pxbrecommended}}}``                                             |
In this release it will be `percona/percona-server-mysql-operator:0.2.0-backup`, so we will not use official PXB image.

2022-06-29 08:32 UTC, spron-in requested changes

2022-06-29 08:32 UTC, spron-in commented on source/backups.rst
> +contains correctly configured keys and is applied with ``kubectl`` command, use
i'm not saying we should mention helm, i think this is not relevant at all.

2022-06-29 08:42 UTC, egegunes commented on source/assets/images/backup-s3.svg
> +<?xml version="1.0" encoding="UTF-8"?>
Well... we both have a sidecar to run backup on and a separate backup pod to trigger backup.

2022-06-29 10:29 UTC, fiowro commented on source/conf.py
>  pmm2recommended = '2.25.0'
thanks, fixed versions in a separate PR

2022-06-29 10:52 UTC, fiowro commented on source/backups.rst
> +* Make sure that the cluster is running.
not yet supported

2022-06-29 10:55 UTC, fiowro commented on source/backups.rst
> +contains correctly configured keys and is applied with ``kubectl`` command, use
we had a ticket some time ago to mention apply command for all cr.yaml edits... Let's discuss it separately and change the wording for all operators at once

2022-06-30 09:20 UTC, tplavcic approved these changes

2022-06-30 09:44 UTC, egegunes approved these changes

2022-06-30 09:46 UTC, merged