Expose ps cluster
percona/percona-server-mysql-operator pull request #117
Opened 2022-07-05 23:50 UTC by fiowro

2022-07-05 23:50 UTC, it-percona-cla commented
[![CLA assistant check](https://cla-assistant.percona.com:443/pull/badge/not_signed)](https://cla-assistant.percona.com:443/percona/percona-server-mysql-operator?pullRequest=117) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.percona.com:443/percona/percona-server-mysql-operator?pullRequest=117) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: fiowro<br/>:x: spron-in<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.percona.com:443/check/percona/percona-server-mysql-operator?pullRequest=117) it.</sub>

2022-07-08 19:18 UTC, spron-in approved these changes
please confirm ports with @egegunes

2022-07-11 12:14 UTC, egegunes requested changes

2022-07-11 12:14 UTC, egegunes commented on source/expose.rst
> +Asyncronous Replication
saw the same typo on multiple places

```suggestion
Asynchronous Replication
```

2022-07-11 12:14 UTC, egegunes commented on source/expose.rst
> +With `Asyncronous or Semi-syncronous replication <https://dev.mysql.com/doc/refman/8.0/en/group-replication-primary-secondary-replication.html>`_
```suggestion
With `Asynchronous or Semi-synchronous replication <https://dev.mysql.com/doc/refman/8.0/en/group-replication-primary-secondary-replication.html>`_
```

2022-07-11 12:14 UTC, egegunes commented on source/expose.rst
> +different replication types: `Asyncronous<https://dev.mysql.com/doc/refman/8.0/en/replication.html>`_
```suggestion
different replication types: `Asynchronous <https://dev.mysql.com/doc/refman/8.0/en/replication.html>`_
```

2022-07-11 12:14 UTC, egegunes commented on source/expose.rst
> +and `Group Replicaiton <https://dev.mysql.com/doc/refman/8.0/en/group-replication.html>`_.
```suggestion
and `Group Replication <https://dev.mysql.com/doc/refman/8.0/en/group-replication.html>`_.
```

2022-07-11 12:14 UTC, egegunes commented on source/expose.rst
> +The following example exposes the Primary node of the asyncronous cluster with
```suggestion
The following example exposes the Primary node of the asynchronous cluster with
```

2022-07-26 12:23 UTC, merged