WIP: Wrong hostname resolution
percona/percona-server-mysql-operator pull request #130
Opened 2022-08-01 14:53 UTC by an3l

Error message raised when new replica occurs with hostname created from `primary.Key.Hostname` based on service name and Namespace -> `.cluster1-mysql.default`, however alias doesn't exist:
```bash
2022-08-01T14:22:09.423Z        ERROR   controller.perconaservermysql   Reconciler error        {"reconciler group": "ps.percona.com", "reconciler kind": "PerconaServerMySQL", "name": "cluster1", "namespace": "default", "error": "reconcile: replication: reconcile semi-sync: connect to .cluster1-mysql.default: ping database: dial tcp: lookup .cluster1-mysql.default: no such host", "errorVerbose": "dial tcp: lookup .cluster1-mysql.default: no such host\nping database\ngithub.com/percona/percona-server-mysql-operator/pkg/replicator.NewReplicator\n\t/go/src/github.com/percona/percona-server-mysql-operator/pkg/replicator/replicator.go:73\ngithub.com/percona/percona-server-mysql-operator/controllers.reconcileReplicationSemiSync\n\t/go/src/github.com/percona/percona-server-mysql-operator/controllers/perconaservermysql_controller.go:1046\ngithub.com/percona/percona-server-mysql-operator/controllers.(*PerconaServerMySQLReconciler).reconcileReplication\n\t/go/src/github.com/percona/percona-server-mysql-operator/controllers/perconaservermysql_controller.go:747\ngithub.com/percona/percona-server-mysql-operator/controllers.(*PerconaServerMySQLReconciler).doReconcile\n\t/go/src/github.com/percona/percona-server-mysql-operator/controllers/perconaservermysql_controller.go:138\ngithub.com/percona/percona-server-mysql-operator/controllers.(*PerconaServerMySQLReconciler).Reconcile\n\t/go/src/github.com/percona/percona-server-mysql-operator/controllers/perconaservermysql_controller.go:109\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/go/src/github.com/percona/percona-server-mysql-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:114\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/src/github.com/percona/percona-server-mysql-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:311\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/src/github.com/percona/percona-server-mysql-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/src/github.com/percona/percona-server-mysql-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:227\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1571\nconnect to .cluster1-mysql.default\ngithub.com/percona/percona-server-mysql-operator/controllers.reconcileReplicationSemiSync\n\t/go/src/github.com/percona/percona-server-mysql-operator/controllers/perconaservermysql_controller.go:1051\ngithub.com/percona/percona-server-mysql-operator/controllers.(*PerconaServerMySQLReconciler).reconcileReplication\n\t/go/src/github.com/percona/percona-server-mysql-operator/controllers/perconaservermysql_controller.go:747\ngithub.com/percona/percona-server-mysql-operator/controllers.(*PerconaServerMySQLReconciler).doReconcile\n\t/go/src/github.com/percona/percona-server-mysql-operator/controllers/perconaservermysql_controller.go:138\ngithub.com/percona/percona-server-mysql-operator/controllers.(*PerconaServerMySQLReconciler).Reconcile\n\t/go/src/github.com/percona/percona-server-mysql-operator/controllers/perconaservermysql_controller.go:109\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/go/src/github.com/percona/percona-server-mysql-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:114\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/src/github.com/percona/percona-server-mysql-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:311\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/src/github.com/percona/percona-server-mysql-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/src/github.com/percona/percona-server-mysql-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:227\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1571\nreconcile semi-sync\ngithub.com/percona/percona-server-mysql-operator/controllers.(*PerconaServerMySQLReconciler).reconcileReplication\n\t/go/src/github.com/percona/percona-server-mysql-operator/controllers/perconaservermysql_controller.go:748\ngithub.com/percona/percona-server-mysql-operator/controllers.(*PerconaServerMySQLReconciler).doReconcile\n\t/go/src/github.com/percona/percona-server-mysql-operator/controllers/perconaservermysql_controller.go:138\ngithub.com/percona/percona-server-mysql-operator/controllers.(*PerconaServerMySQLReconciler).Reconcile\n\t/go/src/github.com/percona/percona-server-mysql-operator/controllers/perconaservermysql_controller.go:109\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/go/src/github.com/percona/percona-server-mysql-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:114\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/src/github.com/percona/percona-server-mysql-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:311\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/src/github.com/percona/percona-server-mysql-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/src/github.com/percona/percona-server-mysql-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:227\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1571\nreplication\ngithub.com/percona/percona-server-mysql-operator/controllers.(*PerconaServerMySQLReconciler).doReconcile\n\t/go/src/github.com/percona/percona-server-mysql-operator/controllers/perconaservermysql_controller.go:139\ngithub.com/percona/percona-server-mysql-operator/controllers.(*PerconaServerMySQLReconciler).Reconcile\n\t/go/src/github.com/percona/percona-server-mysql-operator/controllers/perconaservermysql_controller.go:109\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/go/src/github.com/percona/percona-server-mysql-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:114\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/src/github.com/percona/percona-server-mysql-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:311\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/src/github.com/percona/percona-server-mysql-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/src/github.com/percona/percona-server-mysql-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:227\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1571\nreconcile\ngithub.com/percona/percona-server-mysql-operator/controllers.(*PerconaServerMySQLReconciler).Reconcile\n\t/go/src/github.com/percona/percona-server-mysql-operator/controllers/perconaservermysql_controller.go:110\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/go/src/github.com/percona/percona-server-mysql-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:114\nsigs.k8s [...]

2022-08-01 18:42 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| auto-config | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-130/88b59af/auto-config.log) |
| config | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-130/88b59af/config.log) |
| init-deploy | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-130/88b59af/init-deploy.log) |
| monitoring | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-130/88b59af/monitoring.log) |
| semi-sync | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-130/88b59af/semi-sync.log) |
| service-per-pod | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-130/88b59af/service-per-pod.log) |
| scaling | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-130/88b59af/scaling.log) |
| sidecars | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-130/88b59af/sidecars.log) |
| users | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-130/88b59af/users.log) |
| limits | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-130/88b59af/limits.log) |
| demand-backup | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-130/88b59af/demand-backup.log) |
| gr-init-deploy | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-130/88b59af/gr-init-deploy.log) |
| We run 12 out of 12|

commit: https://github.com/percona/percona-server-mysql-operator/pull/130/commits/88b59af377997a08025a273979e202d6490db734
image: `perconalab/percona-server-mysql-operator:PR-130-88b59af`

2022-08-05 11:27 UTC, egegunes commented
@an3l is this still WIP?

2022-08-05 11:36 UTC, egegunes commented
@an3l could you please share the steps to reproduce, so we can confirm the fix?

2022-08-11 13:02 UTC, an3l commented
@egegunes this is just an partial check (I will change the name of PR to reflect only that), but is not solving the error in the logs.
To obtain the error results, follow PR #103 and check the logs from operator pod.
Here is what log look like for the main image: https://gist.github.com/an3l/445ceb48639f4f13823ab979ae0ba6ac
And here when I have added some logs to inspect: https://gist.github.com/an3l/a62b78e1140db40a29417fe199047537

2022-08-16 12:16 UTC, egegunes commented
I'm worried about the primary hostname if `primary.Alias` is empty string. We need to find a more robust way. @inelpandzic please try to reproduce and fix.

2022-08-27 10:41 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| auto-config | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-130/88b59af/auto-config.log) |
| config | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-130/88b59af/config.log) |
| init-deploy | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-130/88b59af/init-deploy.log) |
| monitoring | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-130/88b59af/monitoring.log) |
| semi-sync | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-130/88b59af/semi-sync.log) |
| service-per-pod | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-130/88b59af/service-per-pod.log) |
| scaling | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-130/88b59af/scaling.log) |
| sidecars | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-130/88b59af/sidecars.log) |
| users | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-130/88b59af/users.log) |
| limits | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-130/88b59af/limits.log) |
| demand-backup | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-130/88b59af/demand-backup.log) |
| gr-init-deploy | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-130/88b59af/gr-init-deploy.log) |
| We run 12 out of 12|

commit: https://github.com/percona/percona-server-mysql-operator/pull/130/commits/88b59af377997a08025a273979e202d6490db734
image: `perconalab/percona-server-mysql-operator:PR-130-88b59af`

2022-09-04 10:14 UTC, inelpandzic requested changes
Hey @an3l , with this `primary.Alias != ""` check we still have the same issue, because a few lines below `primary` is returned and if the `Alias` is empty nothing has changed, `hostname` is still empty and so we have the same thing.

Besides this being empty, I'm curious of how it becomes non-empty at some point, because these errors are seen at the startup and after that it gets OK.

2022-12-20 19:12 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| auto-config | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-130/88b59af/auto-config.log) |
| config | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-130/88b59af/config.log) |
| init-deploy | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-130/88b59af/init-deploy.log) |
| monitoring | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-130/88b59af/monitoring.log) |
| semi-sync | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-130/88b59af/semi-sync.log) |
| service-per-pod | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-130/88b59af/service-per-pod.log) |
| scaling | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-130/88b59af/scaling.log) |
| sidecars | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-130/88b59af/sidecars.log) |
| users | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-130/88b59af/users.log) |
| limits | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-130/88b59af/limits.log) |
| demand-backup | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-130/88b59af/demand-backup.log) |
| gr-init-deploy | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-130/88b59af/gr-init-deploy.log) |
| We run 12 out of 12|

commit: https://github.com/percona/percona-server-mysql-operator/pull/130/commits/88b59af377997a08025a273979e202d6490db734
image: `perconalab/percona-server-mysql-operator:PR-130-88b59af`

2023-03-17 08:21 UTC, hors commented
> Hey @an3l , with this `primary.Alias != ""` check we still have the same issue, because a few lines below `primary` is returned and if the `Alias` is empty nothing has changed, `hostname` is still empty and so we have the same thing.
> 
> Besides this being empty, I'm curious of how it becomes non-empty at some point, because these errors are seen at the startup and after that it gets OK.

@an3l Could you please check this PR and update it otherwise we will close it :(

2023-07-12 07:36 UTC, closed without merging