Leverage docker cache
percona/percona-server-mysql-operator pull request #160
Opened 2022-09-01 09:11 UTC by egegunes

2022-09-01 10:29 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| auto-config | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-160/0673fb6/auto-config.log) |
| demand-backup | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-160/0673fb6/demand-backup.log) |
| init-deploy | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-160/0673fb6/init-deploy.log) |
| gr-init-deploy | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-160/0673fb6/gr-init-deploy.log) |
| monitoring | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-160/0673fb6/monitoring.log) |
| config | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-160/0673fb6/config.log) |
| scaling | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-160/0673fb6/scaling.log) |
| semi-sync | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-160/0673fb6/semi-sync.log) |
| users | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-160/0673fb6/users.log) |
| service-per-pod | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-160/0673fb6/service-per-pod.log) |
| sidecars | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-160/0673fb6/sidecars.log) |
| limits | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-160/0673fb6/limits.log) |
| We run 12 out of 12|

commit: https://github.com/percona/percona-server-mysql-operator/pull/160/commits/0673fb68f3948ea77092ed5624c189f09eb64300
image: `perconalab/percona-server-mysql-operator:PR-160-0673fb6`

2022-09-01 14:51 UTC, hors commented on build/Dockerfile
> +COPY api ./api
How many MBs we will save?

2022-09-04 12:53 UTC, inelpandzic reviewed
Maybe I'm missing something, but I can't see any difference in size with this.

2022-09-05 08:43 UTC, egegunes commented
@hors @inelpandzic it was not about the size but time. since we use multi stage builds final image size won't be changed.

2022-09-05 09:43 UTC, inelpandzic commented
> @hors @inelpandzic it was not about the size but time. since we use multi stage builds final image size won't be changed.

Yeah, makes sense. This is timed with a `time` command, like `time make`:
Without cache: `make  2.99s user 3.00s system 1% cpu 6:58.85 total`
With cache: `make 2.84s user 2.40s system 1% cpu 5:24.40 total`

2022-09-05 09:44 UTC, inelpandzic approved these changes

2022-09-05 15:04 UTC, pooknull approved these changes

2022-09-06 11:02 UTC, hors commented on build/Dockerfile
> -COPY . .
@egegunes I do not see any time build differences  with this line and without :(

2022-09-06 14:25 UTC, pooknull commented
@hors can we delete `/usr/lib/debug/usr/bin` folder in this PR until [DISTMYSQL-190](https://jira.percona.com/browse/DISTMYSQL-190) is done?

2022-09-07 08:06 UTC, hors commented
> @hors can we delete `/usr/lib/debug/usr/bin` folder in this PR until [DISTMYSQL-190](https://jira.percona.com/browse/DISTMYSQL-190) is done?

@pooknull yes, we can do it as a workaround

2022-09-07 10:00 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| auto-config | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-160/87de71b/auto-config.log) |
| config | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-160/87de71b/config.log) |
| demand-backup | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-160/87de71b/demand-backup.log) |
| init-deploy | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-160/87de71b/init-deploy.log) |
| gr-init-deploy | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-160/87de71b/gr-init-deploy.log) |
| monitoring | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-160/87de71b/monitoring.log) |
| scaling | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-160/87de71b/scaling.log) |
| semi-sync | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-160/87de71b/semi-sync.log) |
| service-per-pod | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-160/87de71b/service-per-pod.log) |
| users | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-160/87de71b/users.log) |
| sidecars | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-160/87de71b/sidecars.log) |
| limits | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-160/87de71b/limits.log) |
| We run 12 out of 12|

commit: https://github.com/percona/percona-server-mysql-operator/pull/160/commits/87de71b70bf35dfb74e738405c7285832521e5cf
image: `perconalab/percona-server-mysql-operator:PR-160-87de71b`

2022-09-07 11:11 UTC, pooknull requested changes
Please delete `/usr/lib/debug/usr/bin` folder after `percona-mysql-shell` install to reduce image size

2022-09-07 11:26 UTC, egegunes commented
@pooknull wow thank you

2022-09-07 11:33 UTC, pooknull approved these changes

2022-09-07 12:43 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| auto-config | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-160/5881e12/auto-config.log) |
| config | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-160/5881e12/config.log) |
| We run 2 out of 12|

commit: https://github.com/percona/percona-server-mysql-operator/pull/160/commits/5881e12257c0b27a7866d4e43019c19287f4372e
image: `perconalab/percona-server-mysql-operator:PR-160-5881e12`

2022-09-07 13:02 UTC, hors approved these changes

2022-09-07 13:11 UTC, inelpandzic approved these changes

2022-09-07 16:03 UTC, merged