CLOUD-705 delete unused clusters
percona/percona-server-mysql-operator pull request #200
Opened 2022-10-25 13:21 UTC by nmarukovich

2022-10-25 13:22 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/percona/percona-server-mysql-operator?pullRequest=200) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/percona/percona-server-mysql-operator?pullRequest=200) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/percona/percona-server-mysql-operator?pullRequest=200) it.</sub>

2022-10-25 14:32 UTC, tplavcic submitted a review, later dismissed

2022-10-25 15:04 UTC, hors approved these changes

2022-10-25 15:09 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| auto-config | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-200/12912a6/auto-config.log) |
| config | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-200/12912a6/config.log) |
| one-pod | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-200/12912a6/one-pod.log) |
| We run 3 out of 16|

commit: https://github.com/percona/percona-server-mysql-operator/pull/200/commits/12912a6d74bdb878de354224690534173d656183
image: `perconalab/percona-server-mysql-operator:PR-200-12912a6`

2022-10-25 15:57 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| auto-config | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-200/368c2fb/auto-config.log) |
| demand-backup | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-200/368c2fb/demand-backup.log) |
| init-deploy | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-200/368c2fb/init-deploy.log) |
| gr-init-deploy | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-200/368c2fb/gr-init-deploy.log) |
| monitoring | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-200/368c2fb/monitoring.log) |
| semi-sync | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-200/368c2fb/semi-sync.log) |
| config | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-200/368c2fb/config.log) |
| service-per-pod | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-200/368c2fb/service-per-pod.log) |
| gr-demand-backup | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-200/368c2fb/gr-demand-backup.log) |
| sidecars | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-200/368c2fb/sidecars.log) |
| limits | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-200/368c2fb/limits.log) |
| one-pod | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-200/368c2fb/one-pod.log) |
| version-service | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-200/368c2fb/version-service.log) |
| scaling | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-200/368c2fb/scaling.log) |
| tls-cert-manager | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-200/368c2fb/tls-cert-manager.log) |
| users | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-200/368c2fb/users.log) |
| We run 16 out of 16|

commit: https://github.com/percona/percona-server-mysql-operator/pull/200/commits/368c2fbdbbb5ef01cfe1cd2c12cb83ec185a4cc6
image: `perconalab/percona-server-mysql-operator:PR-200-368c2fb`

2022-10-25 18:04 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| We run 0 out of 16|

commit: https://github.com/percona/percona-server-mysql-operator/pull/200/commits/368c2fbdbbb5ef01cfe1cd2c12cb83ec185a4cc6
image: `perconalab/percona-server-mysql-operator:PR-200-368c2fb`

2022-10-26 04:24 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| We run 0 out of 16|

commit: https://github.com/percona/percona-server-mysql-operator/pull/200/commits/368c2fbdbbb5ef01cfe1cd2c12cb83ec185a4cc6
image: `perconalab/percona-server-mysql-operator:PR-200-368c2fb`

2022-10-26 08:14 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| We run 0 out of 16|

commit: https://github.com/percona/percona-server-mysql-operator/pull/200/commits/8bee86e4afe0070f1c714ba9ed04e6b9f03d61ad
image: `perconalab/percona-server-mysql-operator:PR-200-8bee86e`

2022-10-26 13:17 UTC, tplavcic requested changes

2022-10-26 13:17 UTC, tplavcic commented on Jenkinsfile
> +        gcloud version
do we need it? probably leftover from debugging

2022-10-26 15:03 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| auto-config | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-200/85c9b31/auto-config.log) |
| init-deploy | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-200/85c9b31/init-deploy.log) |
| demand-backup | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-200/85c9b31/demand-backup.log) |
| gr-init-deploy | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-200/85c9b31/gr-init-deploy.log) |
| monitoring | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-200/85c9b31/monitoring.log) |
| semi-sync | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-200/85c9b31/semi-sync.log) |
| config | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-200/85c9b31/config.log) |
| service-per-pod | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-200/85c9b31/service-per-pod.log) |
| gr-demand-backup | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-200/85c9b31/gr-demand-backup.log) |
| sidecars | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-200/85c9b31/sidecars.log) |
| limits | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-200/85c9b31/limits.log) |
| one-pod | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-200/85c9b31/one-pod.log) |
| version-service | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-200/85c9b31/version-service.log) |
| tls-cert-manager | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-200/85c9b31/tls-cert-manager.log) |
| scaling | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-200/85c9b31/scaling.log) |
| users | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-200/85c9b31/users.log) |
| We run 16 out of 16|

commit: https://github.com/percona/percona-server-mysql-operator/pull/200/commits/85c9b315d79b9663bbb46719673b565448a3db5d
image: `perconalab/percona-server-mysql-operator:PR-200-85c9b31`

2022-10-26 15:07 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-200/fbd004d/init-deploy.log) |
| gr-init-deploy | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-200/fbd004d/gr-init-deploy.log) |
| monitoring | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-200/fbd004d/monitoring.log) |
| semi-sync | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-200/fbd004d/semi-sync.log) |
| service-per-pod | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-200/fbd004d/service-per-pod.log) |
| sidecars | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-200/fbd004d/sidecars.log) |
| limits | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-200/fbd004d/limits.log) |
| version-service | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-200/fbd004d/version-service.log) |
| tls-cert-manager | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-ps-operator/PR-200/fbd004d/tls-cert-manager.log) |
| We run 9 out of 16|

commit: https://github.com/percona/percona-server-mysql-operator/pull/200/commits/fbd004d0962bd11eee682cf68211afc9902ddc29
image: `perconalab/percona-server-mysql-operator:PR-200-fbd004d`

2022-10-27 07:38 UTC, merged