Add README and CONTRIBUTING.md
percona/percona-server-mysql-operator pull request #28
Opened 2021-12-27 09:54 UTC by egegunes

2021-12-27 09:55 UTC, egegunes commented on CONTRIBUTING.md
> +Percona welcomes and encourages community contributions to help improve [Percona Kubernetes Operator for Percona Server for MySQL](https://www.percona.com/doc/kubernetes-operator-for-pxc/index.html).
Fix doc link

2021-12-27 09:55 UTC, egegunes commented on CONTRIBUTING.md
> +Another good place to discuss Percona Kubernetes Operator for Percona Server for MySQL with developers and other community members is the [community forum](https://forums.percona.com/categories/kuber
Fix forum link

2021-12-27 09:55 UTC, egegunes commented on CONTRIBUTING.md
> +   When your changes are [ready](e2e-tests/README.md), make a commit, mentioning the Jira issue in the commit message, if any:
Provide README for `e2e-tests`

2021-12-27 09:55 UTC, egegunes commented on CONTRIBUTING.md
> +2. We store the documentation as *.rst files in the [pxc-docs](https://github.com/percona/percona-xtradb-cluster-operator/tree/pxc-docs) branch of the Operator GitHub repository. The documentation is
Fix repo and branch link

2021-12-27 09:55 UTC, egegunes commented on README.md
> +Based on our best practices for deployment and configuration, [Percona Kubernetes Operator for Percona Server for MySQL](https://www.percona.com/doc/kubernetes-operator-for-pxc/index.html) contains e
Fix doc link

2021-12-27 09:55 UTC, egegunes commented on README.md
> +See full documentation with examples and various advanced cases on [percona.com](https://www.percona.com/doc/kubernetes-operator-for-pxc/index.html).
Fix doc link

2021-12-27 10:34 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| semi-sync | passed |
| monitoring | passed |
| sidecars | passed |

commit: https://github.com/percona/percona-server-mysql-operator/pull/28/commits/42cb16ff6c161427d511c8ea6cacb9bd725da4ba
image: `perconalab/percona-server-mysql-operator:PR-28-42cb16f`

2021-12-27 13:18 UTC, it-percona-cla commented
[![CLA assistant check](https://cla-assistant.percona.com:443/pull/badge/not_signed)](https://cla-assistant.percona.com:443/percona/percona-server-mysql-operator?pullRequest=28) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.percona.com:443/percona/percona-server-mysql-operator?pullRequest=28) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.percona.com:443/check/percona/percona-server-mysql-operator?pullRequest=28) it.</sub>

2021-12-28 08:21 UTC, spron-in commented on README.md
> +# Percona Kubernetes Operator for Percona Server for MySQL
```suggestion
# Percona Distribution for MySQL Operator v2
```

2021-12-28 08:21 UTC, spron-in commented on README.md
> +# Percona Kubernetes Operator for Percona Server for MySQL
that is the official name.

2021-12-28 08:21 UTC, spron-in commented on README.md
> +Based on our best practices for deployment and configuration, [Percona Kubernetes Operator for Percona Server for MySQL](https://www.percona.com/doc/kubernetes-operator-for-pxc/index.html) contains e
```suggestion
Based on our best practices for deployment and configuration, [Percona Distribution for MySQL Operator v2](https://www.percona.com/doc/kubernetes-operator-for-pxc/index.html) contains everything you need to quickly and consistently deploy and scale Percona Server for MySQL instances in a Kubernetes-based environment on-premises or in the cloud. It provides the following capabilities:
```

2021-12-28 08:21 UTC, spron-in commented on README.md
> +Based on our best practices for deployment and configuration, [Percona Kubernetes Operator for Percona Server for MySQL](https://www.percona.com/doc/kubernetes-operator-for-pxc/index.html) contains e
@fiowro need to change the link

2021-12-28 08:21 UTC, spron-in commented on README.md
> +Percona welcomes and encourages community contributions to help improve Percona Kubernetes Operator for Percona Server for MySQL.
```suggestion
Percona welcomes and encourages community contributions to help improve open source software.
```

2022-01-06 11:29 UTC, hors commented on CONTRIBUTING.md
> +Your pull request will go through an automated build and testing process, and you will have a comment with the report once all tests are over (usually, it takes about 3 hours).
Now it takes 1 hour :)
```suggestion
Your pull request will go through an automated build and testing process, and you will have a comment with the report once all tests are over (usually, it takes about 1 hour).
```

2022-01-06 11:29 UTC, hors commented on CONTRIBUTING.md
> +
Also we need to add 'Building and automated testing' section. But we can do it via separate PR in next release

https://github.com/percona/percona-xtradb-cluster-operator/blob/main/CONTRIBUTING.md#building-and-automated-testing

2022-01-06 11:30 UTC, hors requested changes

2022-01-06 11:30 UTC, hors commented on README.md
> +See the [Contribution Guide](CONTRIBUTING.md) and [Building and Testing Guide](e2e-tests/README.md) for more information.
[Building and Testing Guide](e2e-tests/README.md) - we do not have it now

2022-01-06 12:34 UTC, hors approved these changes

2022-01-06 12:36 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| semi-sync | passed |
| monitoring | passed |
| sidecars | passed |

commit: https://github.com/percona/percona-server-mysql-operator/pull/28/commits/18704b9fcf3433e68012924606ee4a5b47b7dd4b
image: `perconalab/percona-server-mysql-operator:PR-28-18704b9`

2022-01-06 12:46 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| semi-sync | passed |
| monitoring | passed |
| sidecars | passed |

commit: https://github.com/percona/percona-server-mysql-operator/pull/28/commits/6c8d6b9d7b803edf45a110809d53c9bb073d52dd
image: `perconalab/percona-server-mysql-operator:PR-28-6c8d6b9`

2022-01-06 13:11 UTC, fiowro approved these changes
LGTM

2022-01-06 13:32 UTC, merged